### ISSUE TITLE
アクセス時に再生の案内をする

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/Emoine#72]
右下からオーバーレイ解除して左から再生するのを案内するようにする

**Comment by FujishigeTemma** [comment]
これ再生開始ってできないんだっけ？

**Comment by sapphi-red** [comment]
それはブラウザの制約上無理
たまに自動再生されるしたまにされないみたいなのはできるけど結局って感じ

**Comment by sapphi-red** [comment]
デフォルト、オーバーレイoffで、オーバーレイじゃないときは再生ボタンの上に「ここで再生して」、右下のオーバーレイを切り替えるボタンで「ここでスタンプを表示」とかつけると解決するかもしれない
