### ISSUE TITLE
発表者がリアルタイムで確認できるような何かがほしそう

### ISSUE THREAD

**Issue by sapphi-red** [traPtitech/Emoine#79]

**Comment by FujishigeTemma** [comment]
PinPで流れるコメ欄を作ると良さそう

**Comment by sapphi-red** [comment]
PinPでやろうとすると

  Canvas書き込み→それをなんたらAPIでキャプチャ→それをvideoタグのsrcObjectに指定→そのvideoタグをrequestPinP

みたいな闇実装になるから普通にelectronとかで最前面固定のちっさいアプリつくるほうがよさそう

**Comment by FujishigeTemma** [comment]
YouTubeのチャットをポップアップはチャット欄だけ表示するウインドを別で出す感じだからそれで良さそう
参考: https://www.youtube.com/live_chat?is_popout=1&v=RxytWppYJq8

**Comment by sapphi-red** [comment]
それ最前面表示はできなくない？
ディスプレイ一つしか持ってない人のこと考えるとそれだとあんまりうれしくなさそう

**Comment by FujishigeTemma** [comment]
どうだろ、わざわざ別のやついれること考えると僕は小さいウインドウ出してくれるほうが良いけど

**Comment by sapphi-red** [comment]
3331e7af1925c66b6e801afca10a575cb9b0e2c9 で実装済み
